= reacties

2019-08-28
Het artikel is onderdeel van een serie van 6, waarin ik op zoek ging naar zoveel mogelijk data. (zie https://www.roelbazuin.nl/project/augustus/). Ik wilde weten wie die 'alle slachtoffers' nu waren die herdacht worden op 15 augustus.

Zoals bekend bestaat het overgrote deel van relevante data uit 'schattingen'. Dat is tragisch en lastig. De 'schattingen' van dhr. Frederick mbt 'de 10%' wordt uitgebreid becritiseerd. Ik heb zijn 'schatting', net als de rest, opgenomen in de tabel. Wellicht komt er op enig moment betere en onderbouwde 'schattingen'.

Het 'aantal vermisten' is gebaseerd op een NIOD artikel: http://niodbibliotheek.blogspot.com/2014/05/de-slachtoffers-van-de-bersiap_16.html waarbij de Jong wordt aangehaald.

In elk geval is me duidelijk geworden dat ~ 95% van de slachtoffers in NEI niet wordt herdacht. Dat is behalve tragisch schaamteloos en eerlijk gezegd verbijsterend.

--
@Boeroeng
Ik meen dat het artikel duidelijk is over uitgangspunten en doelstellingen.. Ik ben uitgegaan van https://15augustus1945.nl. De officiele landelijke herdenking.

Je hebt volkomen gelijk: iedereen herdenkt zijn of haar eigen verlies in WOII. Of niet. 
"Ik gedenk. En herdenk. Net even iets anders." (https://www.roelbazuin.nl/blog/herdenking.html)

Ik vermoed dat ik niet de enige ben die op zoek is naar patronen in gerelateerde dossiers, bv. 'de Indische kwestie', het lopende 'dekolonisatie' onderzoek, etc. Dit onderzoekje was in eerste instantie voor mezelf door het op een rij zetten van relevante data.

Ik heb alle txt deze keer bewust op Github /Bitpucket gezet. Iedereen kan het gebruiken, aanvullen etc. Of niet.

2019-09-04

In 6 artikelen ging ik op zoek naar een antwoord op 'niet ALLE slachtoffers worden -officieel- herdacht op de Nationale Herdenking'. 

August 2019
26 - Project Augustus - Nationale Herdenking Nederlands-Indië - Slachtoffers tussen 1942 en 1963 - 95% wordt vergeten -
23 - Project Augustus - Herdenking Nederlands-Indië 1945 - Burger slachtoffers tussen augustus '45 en 1963
22 - Project Augustus - Herdenking Nederlands-Indië 1945 - Slachtoffers Militairen tussen augustus '45 en 1963
21 - Project Augustus - Herdenking Nederlands-Indië 1945 - Burger slachtoffers vòòr 15 augustus '45
19 - Project Augustus - Herdenking Nederlands-Indië 1945 - Slachtoffers Militairen vòòr 15 augustus '45
18 - Project Augustus - Herdenking slachtoffers Nederlands-Indië 1945 

Niet onverwacht is er veel aandacht voor de periode '45-63'. Het hier aangehaalde deel 5.

Wat iemand er ook van vindt: Bij de - in 1970 gestartte - 'Nationale herdenking' worden op zijn minst 4.380.000 slachtoffers vergeten.

https://www.roelbazuin.nl/project/augustus/#_alle_statistiek_bij_elkaar

2019-09-04
@boeroeng ea Ik vertel wat de  opzet is van mijn 6 artikelen. In hoofdzaak het verzamelen van data. Het is -ook mij- bekend dat ze elkaar hier en daar tegenspreken en al dan niet hiermee samenhangend grond zijn voor vingertjes en wat al niet.

Op een ander moment in de discussie hier heb ik u op een vergelijkbare opmerking ook niet tegengesproken. U heeft gelijk. Eenieder herdenkt die hij wil. Uitstekend. En kan de beschikbare en elkaar tegensprekende aantallen bediscussiëren. Prima.

Voor de duidelijkheid: ik heb het artikel over 'Burger slachtoffers tussen augustus '45 en 1963' niet zelf hier geplaatst. De serie van 6 was enerzijds primair bedoeld als 'persoonlijk context' voor mijn stamboom onderzoek en anderzijds als 'historische context' om na te gaan wie al die slachtoffers zijn die worden herdacht. 

Ik heb wel een mening over het gebrek aan historische besef in dit land. Je zou kunnen zeggen dat in deze context, gebaseerd op de serie van 6, het gebrek eraan nog erger is dan ik al dacht. Zeker als het gaat om Nederlands-Indië.

Voor de liefhebbers alle tot op heden verzamelde data in 14 tabellen bij elkaar.
http://roelbazuin.nl/project/augustus/augustus_1945_1963_tabellen.html

Overigens: Het aantal militaire en burger slachtoffers in de Pacific regio is rond 36.000.000. Anders gezegd: 50% van alle slachtoffers in de tweede wereldoorlog. Ik herdenk ze allemaal en hoop en wens tegelijk dat mijn kinderen en kleinkinderen dat niet hoeven te doen bij een herhaling van vergelijkbaar menselijk gedrag.