= Project Augustus - Slachtoffers voor en na augustus 1945 in Nederlands-Indië / Indonesië
.
2019-08-17
:author: Roel Bazuin
// custom meta
// Opmaak
:source-highlighter: rouge
:icons: font
// turn section titles into . links
:sectlinks:
//:sectnums:
//:leveloffset:
:allow-uri-read:
:description:  augustus herdenkingen
:jbake-tags: blog,augustus
// Type 
// :jbake-type: post
:jbake-type: page
// Status
// :jbake-status: published
:jbake-status: draft
// - providing content date is equal to or past current date content will be considered published and included in the published collections
:publish_date: 2019-08-17
:revdate: 2019-09-02
//
:doctype: book
:toc: left
//:toc: macro
:toc-title: Inhoud Project Augustus

toc::[]

//:imagesdir: 
// referenties
:ref1: ‘Moord op duizenden (Indische) Nederlanders was genocide’ - https://indisch4ever.nu/2013/11/21/moord-op-duizenden-indische-nederlanders-was-genocide/
:ref2: https://www.thejakartapost.com/news/2013/11/12/the-untold-story-surabaya-battle-1945.html
:ref3: Opmerkelijke feiten en zaken aangaande Nederlands Indië/Indonesië - https://indisch4ever.nu/2011/12/27/opmerkelijke-feiten-en-zaken-aangaande-nederlands-indieindonesie/
:ref4: https://indisch4ever.nu/2013/11/21/the-bersiapdiscussion-as-revived-by-w-frederick/
:ref4: 100.000: the magic victim number - https://www.kitlv.nl/blog-100-000-magic-victim-number/
:ref5: Bersiap: de werkelijke cijfers (2014) - https://javapost.nl/2014/02/07/bersiap-de-werkelijke-cijfers/
:ref6: De slachtoffers van de Bersiap - http://niodbibliotheek.blogspot.com/2014/05/de-slachtoffers-van-de-bersiap_16.html
//
:bersiap: Bersiap - https://en.wikipedia.org/wiki/Bersiap
:bersiapincijfers: Bersiap in cijfers - https://javapost.nl/2012/09/03/bersiap-in-cijfers/
:nidobersiap: http://niodbibliotheek.blogspot.com/2014/05/de-slachtoffers-van-de-bersiap_16.html
:vj: Victory over Japan Day - https://en.wikipedia.org/wiki/Victory_over_Japan_Day
//
:eindspel: Eindspel Indische kwestie - https://indisch4ever.nu/2015/11/20/eindspel-indische-kwestie

_^Eerste^ ^versie^ ^geschreven^ ^op^ ^{publish_date}^_ +
//Artikelen over '{author_name}' door {author} +
//Version date: {revdate} +

include::inleiding_nl.adoc[]

// #woii #herdenken #gedenken #nadenken

// deel 1 Herdenking

= De Nationale Herdenking van slachtoffers in Nederlands-Indië


== Vergeten ..

include::augustus_1945_herdenking.adoc[tag=deel1]

// deel 2
// Militaire slachtoffers
// deel inleiding meegenomen
.[big]*Wie worden er precies herdacht?*

include::augustus_1945_army_victims.adoc[tag=deel2]

// deel 3
// Burgerslachtoffers

include::augustus_1945_civilian_victims.adoc[tag=deel3]


//deel 4

= Slachtoffers tussen augustus '45 en 1963

== Militairen

include::augustus_1945_1963_army_victims.adoc[tag=deel4]

== Burgers
// Burgerslachtoffers
// deel 5

include::augustus_1945_1963_civilian_victims.adoc[tag=deel5]


// deel 6

= Samenvatting statistiek

include::augustus_1942_1963_statistiek_totaal.adoc[tag=deel6]

:!sectnums!:

:appendix-caption: Appx
//:sectnums:
//:leveloffset!: 
//== Bijlagen
//=== Casualties in Asia and the Pacific by nation and type
//include::includes/casualties_in_asia.adoc[tag=table]

= Quotes
Enkele Citaten die letterlijk of impliciet zijn gebruikt.

. "_Herman Bussemaker : +
“De Indonesische vrijheidsstrijd bestaat in feite uit drie afzonderlijke conflicten die tegelijkertijd speelden. In de eerste plaats was er natuurlijk de interstatelijke oorlog tussen Nederland en Indonesië, ruwweg van 1947 tot en met 1949. Tegenover de 6.000 omgekomen Nederlandse militairen en circa 10.000 omgekomen Nederlandse burgers staan, zo schat ik, circa 30.000 omgekomen Indonesiërs. Het gaat zowel om militairen als burgers._ +
_De meeste doden vielen daarbij in de strijd tussen de centrale regering van Soekarno/Hatta en separatistische Indonesische organisaties als de PKI (communisten)._
_Naast deze burgeroorlog tussen Indonesiërs onderling +was er sprake van een tweede conflict tussen Indonesiërs en groepen Indonesiërs die verdacht werden van Nederlandse sympathieën. Het bekendst zijn de Zuid-Molukkers. Maar ook andere Indonesiërs werden met hele families tegelijk van kant gemaakt. Ook de Indo-Chinese gemeenschap betaalde een zware tol vanwege hun welvaart en vermeende Nederlandse affiniteit._ +
_Hoewel geen Indonesiërs, waren ook de Indische Nederlanders het kind van de rekening tijdens de bersiap-periode vanwege hun loyaliteit aan het Nederlandse bestuur. Tussen oktober 1945 en begin 1946 zijn zeker 3.500 Indische Nederlanders, meest vrouwen en kinderen, vermoord. Door ondervoeding stierven nog duizenden kinderen en ouderen in de bersiap-kampen._

. _Deze drie gelijktijdige oorlogen tijdens de Indonesische vrijheidsstrijd maken een historisch verantwoorde geschiedschrijving van de Indonesische revolutie uitermate complex."_ +
P.Lemon op indisch4ever.nu - 2013_footnote:[{ref1}]

. Volledigheidshalve moet vermeld worden dat ca. 230.000 Indischen naar Nederland zijn overgekomen en ca. 4.000.000 ( incl. niet “erkende”) in Indonesië zijn geblevenfootnote:[{ref3}].

. Doordat de totoks in door de Japanners” beschermde”kampen zaten werd de tol! van dit beleid door Indo families (veelal met kleine kinderen), gedragen. En dat, na bijna 3,5 jaar Jappen tijd, zonder vaste (echtgenoot) inkomsten met oma/opa tjattoeten( om voedsel handelend) om deze benarde tijd levend doorheen te komenfootnote:[ing.R.L.Mertens - {ref3}].

. Mij steekt alleen dat wij in Nederland, incl. de Indische gemeenschap, onze doden in Indonesië aan het vergeten zijn. Wij mogen ze zelfs niet herdenken op 15 augustus bij het Indisch Monument!footnote:[Jan A. Somers - {ref3}]

. _But we can ask why the information is not better know, and has not attracted more interest over the years? Those are very difficult and complex questions, and certainly no single response is adequate. +
Survivors, and the families of those who did not survive, have been very quiet about this dark past, and the reasons are not entirely clear. For some, it was too horrible to re-tell; for others, feelings of guilt that somehow they had been complicit with the evils of colonial oppression have kept them silent. Some perhaps were also silenced by the racial prejudices of the Dutch society around them after arriving in the Netherlands, and feared as well that stories of their experiences would not be believed. +
And many probably simply wanted to leave the bersiap behind them entirely, and refused to burden their children and grand children with what they knew about that history, which they believed was no longer relevant_ footnote:[William H Frederick - {ref1}]. 

. Een beetje indo die de Jappenkampen heeft overleefd weet zijn weg wel te vinden. Zo iemand dopt zijn eigen boontjes. Is blij dat hij nog leeft. En hij haalt zijn neus niet op voor de geur van andijvie (of spruitjes). Zo iemand toch, heeft de lucht van lijken reeds ingeademdfootnote:[Ed Vos - {ref5}].

= Afkortingen

[glossary]

O.D.O.:: Nederlandse Opsporingsdienst Overledenen (ODO).  +
In december 1945 opgerichte organisatie was belast met het verzamelen van betrouwbare gegevens over alle Nederlanders en Nederlandse onderdanen die na 7 december 1941 waren overleden of werden vermist. Helaas is van het O.D.O.-archief zeer weinig bewaard gebleven. 

KNIL-ML:: Militaire Luchtvaart Koninklijk Nederlands Indisch Leger
KNIL:: Koninklijk Nederlands-Indisch Leger
MLD:: Marine Luchtvaartdienst 

NEI:: Netherlands East Indies