== Inleiding

=== Project Augustus

//A public experiment on Github when writing articles with lots of data, references and tables. 
Project Augustus is een publiek experiment op Github bij het schrijven van artikelen (in Asciidoc) met veel achterliggende data en referenties. 
De eerste 'commit' was op 18 augustus 2019.

https://github.com/tjitjak/augustus

Ook op Bitbucket:

https://bitbucket.org/tjitjak/augustus/src/master/


//# About
=== Over

//"_Commemoration of victims after August 1945_"
"Herdenking van [underline]*alle slachtoffers* in voormalig Nederlands-Indië"

//"For the - first generation - Dutch Indo-Europeans, in addition to the Japanese occupation, the period August 1945 - 1950 is a timeframe in which once again victims fell who should not be forgotten."
"Voor de - eerste generatie - Nederlandse Indo-Europeanen, zijn er slachtoffers te gedenken voor en na augustus 1945. Ook diegenen die zijn gevallen tussen augustus 1945 en 1963 dienen niet te worden vergeten"

//_The plan is to make additional documents with the number of victims before and after August 1945._

//# Content
=== Inhoud

- https://github.com/tjitjak/augustus/tree/master/docs[Docs] +
//This directory holds all documents. All written in asciidoc. They will be pushed to Jbake for publishing on my website.
In deze directory staan alle asciidoc documenten. Zij worden met Jbake op mijn website - http://roelbazuin.nl -  gepubliceerd.

** https://github.com/tjitjak/augustus/tree/master/includes[Includes] +
//Holds documents and files to be used in a main doc as an 'include'.
Documenten met data. Zij worden middels een 'include' gebruikt in een hooddocument.

- https://github.com/tjitjak/augustus/tree/master/output[Output] +
//Holds pdf and HTML documents
Directory met pdf en html bestanden. Output van /docs. 


=== Copyright and License

Copyright 2019 Roel Bazuin. Documents released under the MIT license.

---
